docs/UAA-LDAP.md
The LDAP Group bean prepends the ldap.groups.file with "WEB-INF/spring/" automatically and should not be included in the yml.
Also fixed two cases where "`'s`" should just be "`s`"
Author: Josh Ghiloni <jghiloni@ecsteam.com>
=> Fix possessive typos, fix ldap.groups.file to use correct path

docs/UAA-APIs.rst
Creating clients requires a `POST` to `/oauth/clients`, not to `/oauth/clients/{client_id}`. Verified against UAA 2.0
Author: Josh Ghiloni <jghiloni@ecsteam.com>
=> Fix Create Client Endpoint

common/src/main/java/org/cloudfoundry/identity/uaa/oauth/ClientAdminEndpoints.java
Method needs annotation with @ResponseBody to avoid Spring applying the default view behaviour and treating it as a template.
Previously /oauth/clients/{client}/secret caused an internal server error since the template it was looking for didn't exist.
=> ResponseBody annotation on changeSecret

common/src/main/java/org/cloudfoundry/identity/uaa/oauth/UaaAuthorizationRequestManager.java, common/src/test/java/org/cloudfoundry/identity/uaa/oauth/UaaAuthorizationRequestManagerTests.java
It looks like the empty scope message was unintentionally mangled as part of a rename aimed at code - this PR reinstates the original message.  It's certainly quite confusing to encouter the current one!
I've also extended the existing test to cover the text of the message.
=> Reinstate original empty scopes error message

docs/UAA-APIs.rst
It does not take a client-id as part of the URL.
=> Fix "Register Client" endpoint doc

docs/UAA-Tokens.md
The old link provided is expired "https://developers.google.com/wallet/digital/docs/jwtdecoder". No more helping the user.
This link is an easy way to see the token body http://jwt.calebb.net/.
Also very detailed writings are available here dealing with the body of the token. https://developers.google.com/accounts/docs/OpenIDConnect#validatinganidtoken
=> docs/UAA-Tokens.md - Fix pointing to the appropriate Links for decoder and tokens.

common/src/main/java/org/cloudfoundry/identity/uaa/authentication/manager/AuthEvent.java, common/src/main/java/org/cloudfoundry/identity/uaa/codestore/ExpiringCodeStore.java, common/src/main/java/org/cloudfoundry/identity/uaa/config/CustomPropertyConstructor.java, common/src/main/java/org/cloudfoundry/identity/uaa/config/PasswordPolicy.java, common/src/main/java/org/cloudfoundry/identity/uaa/config/YamlConfigurationValidator.java, common/src/main/java/org/cloudfoundry/identity/uaa/config/YamlMapFactoryBean.java, common/src/main/java/org/cloudfoundry/identity/uaa/config/YamlProcessor.java, common/src/main/java/org/cloudfoundry/identity/uaa/error/UaaException.java, common/src/main/java/org/cloudfoundry/identity/uaa/ldap/extension/DefaultLdapAuthoritiesPopulator.java, common/src/main/java/org/cloudfoundry/identity/uaa/ldap/extension/NestedLdapAuthoritiesPopulator.java, common/src/main/java/org/cloudfoundry/identity/uaa/login/saml/FixedHttpMetaDataProvider.java, common/src/main/java/org/cloudfoundry/identity/uaa/oauth/ClientDetailsValidator.java, common/src/main/java/org/cloudfoundry/identity/uaa/oauth/RemoteTokenServices.java, common/src/main/java/org/cloudfoundry/identity/uaa/oauth/token/SignerProvider.java, common/src/main/java/org/cloudfoundry/identity/uaa/security/web/SecurityFilterChainPostProcessor.java, common/src/main/java/org/cloudfoundry/identity/uaa/util/UaaStringUtils.java, common/src/main/java/org/cloudfoundry/identity/uaa/zone/IdentityZoneSwitchingFilter.java, common/src/main/java/org/cloudfoundry/identity/uaa/zone/UaaIdentityProviderDefinition.java, login/src/main/java/org/cloudfoundry/identity/uaa/login/util/IndirectBeanCreator.java, samples/app/src/main/java/org/cloudfoundry/identity/app/web/HomeController.java, scim/src/main/java/org/cloudfoundry/identity/uaa/scim/bootstrap/ScimExternalGroupBootstrap.java, scim/src/main/java/org/cloudfoundry/identity/uaa/scim/bootstrap/ScimGroupBootstrap.java, scim/src/main/java/org/cloudfoundry/identity/uaa/scim/validate/UaaPasswordPolicyValidator.java, scim/src/test/java/org/cloudfoundry/identity/uaa/scim/endpoints/PasswordResetEndpointTest.java, uaa/src/test/java/org/springframework/security/ldap/server/ApacheDsSSLContainer.java
The project can now be build with Java 7 and Java 8 with all tests passing.
We now support to build uaa with Java 8 via ``./gradlew clean build.``
This PR contains fixes for all JavaDoc errors and some JavaDoc warnings.
Refactored ``ApacheDsSSLContainer`` used for LDAP tests to avoid using internal
com.sun.* API that is not available in Java 8 (e.g. ``CertAndKeyGen``).
Fixed some test cases in ``PasswordResetEndpointTest``
- ``changePassword_Returns422UnprocessableEntity_NewPasswordSameAsOld``
- ``testPasswordsMustSatisfyPolicy``
that failed under Java 8 because to different ordering of the resulting JSON objects due to internal changes in the underlying ``HashMap`` implementation.
The provided ``JsonObjectMatcher`` provides support for property order in-sensitve matching of ``JSON …
=> Allow to build uaa with Java 8.

uaa/src/main/webapp/WEB-INF/spring-servlet.xml
In our organization we don't use Email we use ldap integration so we would prefer to prompt for a "Username".
This PR provides initial support for getting username and password prompts from configuration keeping the default the same as the previous value.  If this PR gets accepted I can submit one to support prompt configuration in cf-release.
I find it odd nobody has done this already.  So, if I'm missing something a pointer in the correct direction would be great.
=> Support customization of Login and Password prompts

samples/app/src/main/webapp/login_error.jsp
We now use the `WebAttributes.AUTHENTICATION_EXCEPTION` key as a replacement for the (deprecated) and in the meantime removed constants from `AbstractAuthenticationProcessingFilter`.
=> Fix extraction of authentication exception in sample.

common/src/main/java/org/cloudfoundry/identity/uaa/UaaConfiguration.java, common/src/main/java/org/cloudfoundry/identity/uaa/web/CorsFilter.java, common/src/test/java/org/cloudfoundry/identity/uaa/web/CorsFilterTests.java, uaa/src/main/resources/uaa.yml
We rolled the CORS changes out into our staging environment and our front-end development teams discovered that they we needed to relax our policy on allowed headers. Thus, I made allowed headers configurable. I also discovered some issues with the validation of configuration properties while deploying and fixed those.
These changes have been tested in our staging environments by teams building single page JS apps that makes CORS XHR requests in Firefox and Chrome.
=> Modified CORS filter so that allowed headers for XHR requests is configurable.

common/src/main/java/org/cloudfoundry/identity/uaa/oauth/Claims.java, common/src/main/java/org/cloudfoundry/identity/uaa/oauth/token/UaaTokenServices.java, uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/token/TokenMvcMockTests.java
OpenID Connect implementation doesn't respect *nonce* sent from client, while it must do that.
Here is the implementation of the feature.
This fixes [cfid-3214](https://www.pivotaltracker.com/n/projects/997278/stories/82159480)
Formal description from http://openid.net/specs/openid-connect-core-1_0.html#IDToken
**nonce**
*String value used to associate a Client session with an ID Token, and to mitigate replay attacks. The value is passed through unmodified from the Authentication Request to the ID Token. If present in the ID Token, Clients MUST verify that the nonce Claim Value is equal to the value of the nonce parameter sent in the Authentication Request. If present in the Authentication Request, Authorization Servers MUST include a nonce Claim in the ID Token with the Claim Value being …
=> Respect nonce

common/src/main/java/org/cloudfoundry/identity/uaa/oauth/token/TokenKeyEndpoint.java, uaa/src/main/webapp/WEB-INF/spring/resource-endpoints.xml, uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/token/TokenKeyEndpointMockMvcTests.java
New "token_keys" endpoint returns token key wrapped in "keys" array.
Some clients may require this format (like mod_auth_openidc).
See JWKS Set Format defined in RFC 7517: https://tools.ietf.org/html/rfc7517#section-5
Real world example: https://www.googleapis.com/oauth2/v3/certs
=> New "token_keys" endpoint (JWKS Set Format)

common/src/main/java/org/cloudfoundry/identity/uaa/oauth/Claims.java, common/src/main/java/org/cloudfoundry/identity/uaa/oauth/token/UaaTokenServices.java, common/src/test/java/org/cloudfoundry/identity/uaa/oauth/token/UaaTokenServicesTests.java
A number of our users are building multi-tenant applications which receive tokens from zones with multiple identity providers. In some scenarios they need to know what identity provider authenticated the user. Also this can be useful to disambiguate users from different identity providers with the same username.
=> Added origin in JWT token and refresh token.

common/src/main/resources/spring/data-source.xml, login/src/main/java/org/cloudfoundry/identity/uaa/login/util/LocalUaaRestTemplate.java
Adding the missing flyway dependency will ensure the correct order of bean initialization. Using an interface for tokenServices allows the implementation to be overridden in configuration.
=> Add missing flyway dependency and use interface for tokenServices

build.gradle
This commit fixes an issue we've observed when using cargoRunLocal to launch UAA
during the BOSH integration tests:
```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':cargoRunLocal'.
at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
at …
```
=> Fixed ContainerException when cargoRunLocal is invoked more than once

common/src/main/java/org/cloudfoundry/identity/uaa/authentication/manager/AuthEvent.java, common/src/main/java/org/cloudfoundry/identity/uaa/authentication/manager/ExternalGroupAuthorizationEvent.java, common/src/main/java/org/cloudfoundry/identity/uaa/authentication/manager/LdapLoginAuthenticationManager.java, common/src/main/java/org/cloudfoundry/identity/uaa/authentication/manager/NewUserAuthenticatedEvent.java, scim/src/main/java/org/cloudfoundry/identity/uaa/scim/bootstrap/ScimUserBootstrap.java, scim/src/test/java/org/cloudfoundry/identity/uaa/scim/bootstrap/ScimUserBootstrapTests.java
This is an attempt at fixing Issue https://github.com/cloudfoundry/uaa/issues/176.
I tried all kinds of less intrusive fixes but nothing worked.
Setting version=-1 gets undone by:
https://github.com/cloudfoundry/uaa/blob/master/scim/src/main/java/org/cloudfoundry/identity/uaa/scim/jdbc/JdbcScimUserProvisioning.java#L226
I prepared a patch for this but that didn't fix it either because when ldap updates the user is also updates the password since the password is always bogus which causes existing tokens to be invalidated:
https://github.com/cloudfoundry/uaa/blob/master/scim/src/main/java/org/cloudfoundry/identity/uaa/scim/bootstrap/ScimUserBootstrap.java#L136
So, finally instead of trying the fragile solution of making ldap's update of a user not intrusive I decided to attempt to just fix …
=> Only update the user if the event says to do so

common/src/main/resources/org/cloudfoundry/identity/uaa/db/hsqldb/V2_7_4__Fix_Client_Id_Length.sql, common/src/main/resources/org/cloudfoundry/identity/uaa/db/mysql/V2_7_4__Fix_Client_Id_Length.sql, common/src/main/resources/org/cloudfoundry/identity/uaa/db/postgresql/V2_7_4__Fix_Client_Id_Length.sql, common/src/test/java/org/cloudfoundry/identity/uaa/oauth/token/UaaTokenStoreTests.java
Test with a long client id in UaaTokenStoreTests.
Fixes #239.
[#105230034]
https://www.pivotaltracker.com/story/show/105230034
=> Set the client_id column to varchar(255) in oauth_code table.

common/src/main/java/org/cloudfoundry/identity/uaa/login/saml/IdentityProviderConfigurator.java, common/src/test/java/org/cloudfoundry/identity/uaa/login/saml/IdentityProviderConfiguratorTests.java, uaa/src/main/resources/login.yml
Same as https://github.com/cloudfoundry/uaa/pull/217, but this time against `develop` and with test cases:
At the moment, it is not possible to specify the newly introduced property addShadowUserOnLogin for saml providers in login.yml - in the database, it always ends up as "addShadowUserOnLogin":false.
This PR extends the IdentityProviderConfigurator to respect the this property also - so it can be specified in login.yml.
I also added the property in the example configurations in login.yml (this is only for demonstration, it still defaults to true to not break things).
=> SAML provider: possibility to specify 'addShadowUserOnLogin' in login.yml

docs/UAA-APIs.rst
RFC 6749 is the latest proposed standards document for the OAuth 2.0 framework.
=> Update UAA API docs to refer to OAuth 2.0 standard

build.gradle
We now use the "org.flywaydb.flyway" gradle plugin in.
The previously used "flyway" id caused a deprecation warning:
```
The 'flyway' plugin ID is deprecated and will be removed in Flyway 4.0. Update your build to use 'org.flywaydb.flyway' instead.
```
=> Use new plugin id for gradle flyway plugin.

.travis.yml, server/src/main/java/org/cloudfoundry/identity/uaa/message/EmailService.java, server/src/main/resources/login-ui.xml, server/src/test/java/org/cloudfoundry/identity/uaa/login/EmailServiceTests.java, uaa/src/test/java/org/cloudfoundry/identity/uaa/login/BootstrapTests.java, uaa/src/test/resources/test/bootstrap/bootstrap-test.yml
This adds support for login.smtp.from_address to be used for all emails sent by UAA.
@fhanik This is the change we [discussed on slack](https://cloudfoundry.slack.com/archives/uaa/p1462400170000392) with the additional tests your requested.
Feedback appreciated.
=> Allow for specifying the from address used in emails sent by UAA

model/src/main/java/org/cloudfoundry/identity/uaa/provider/AbstractXOAuthIdentityProviderDefinition.java, server/src/main/java/org/cloudfoundry/identity/uaa/provider/oauth/OauthIdentityProviderDefinitionFactoryBean.java, server/src/main/java/org/cloudfoundry/identity/uaa/provider/oauth/XOAuthAuthenticationManager.java, server/src/test/java/org/cloudfoundry/identity/uaa/provider/oauth/XOAuthAuthenticationManagerTest.java, uaa/src/main/resources/login.yml, uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/providers/IdentityProviderEndpointsDocs.java
Fix issue when validating the token's issuer(iss) coming back from an external identity provider. Previously the tokenUrl was used as the value the issuer was compared against. This may not always be the case and so a new configuration item (issuer). If "issuer" is set it will be used instead of the tokenUrl.
=> External Identity Providers issuer validation issue #392

shared_versions.gradle
HttpClient before 4.3.6 is vulnerable, see
https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2015-5262
=> Upgrade to HTTP client 4.3.6

server/src/main/java/org/cloudfoundry/identity/uaa/provider/saml/idp/IdpMetadataGeneratorFilter.java, server/src/main/java/org/cloudfoundry/identity/uaa/provider/saml/idp/IdpWebSsoProfileImpl.java, server/src/main/java/org/cloudfoundry/identity/uaa/provider/saml/idp/SamlServiceProviderConfigurator.java, server/src/test/java/org/cloudfoundry/identity/uaa/provider/saml/idp/IdpWebSsoProfileImplTest.java, server/src/test/java/org/cloudfoundry/identity/uaa/provider/saml/idp/SamlServiceProviderConfiguratorTest.java, server/src/test/java/org/cloudfoundry/identity/uaa/provider/saml/idp/SamlTestUtils.java, uaa/src/test/java/org/cloudfoundry/identity/uaa/provider/saml/SamlIDPRefreshMockMvcTests.java
Signed-off-by: Dario <amiri@ge.com>
=> Add support for SAML NameIDPolicy

server/src/main/java/org/cloudfoundry/identity/uaa/provider/JdbcIdentityProviderProvisioning.java, server/src/main/java/org/cloudfoundry/identity/uaa/provider/saml/idp/JdbcSamlServiceProviderProvisioning.java
* boolean literal search without assigment is valid for most database. SAP HANA does not allow such a where clause. With the prepared statement the assignment to true is valid for all.
=> Change select statement for active providers

server/src/main/java/org/cloudfoundry/identity/uaa/authentication/manager/LoginAuthenticationManager.java, server/src/test/java/org/cloudfoundry/identity/uaa/authentication/manager/LoginAuthenticationManagerTests.java, uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/LoginServerSecurityIntegrationTests.java
A quick bug fix for an ArrayOutOfBoundsException we encountered. I don't know why the family name is extracted from the email, but I have no insight to this project. Hence I tried to touch as few code as possible.
Found with the help of Holger Koser.
An integration test is included. In case you want to manually reproduce the error, try the following steps.
Given $TOKEN contains a valid token for user login, the following http request led to an error:
curl 'https://uaa.cf...../authenticate' -d "source=login&origin=ldap&username=newuser&add_new=true&email=wrongformat" -H 'Accept: application/json' -H "Authorization: bearer $TOKEN" -s -k
Response: {“error":"error"}
Upon inspecting the server logs we found:
RemoteAuthenticationEndpoint: Failed to authenticate user …
=> Fix array out of bounds exception in case of bogus email format

build.gradle
It has been known for a long time that its important to use HTTPS for maven repositories to avoid attacks on developers, build systems, and end users.
This commit updates repos to use HTTPS and more up to date spring.io domains.
It also removes the objectstyle.org maven repo which doesn't seem to be used, is http-only, and seems likely to go away eventually [1]
[1] http://www.objectstyle.com/objectstyle-org-and-community-roots
=> Only use HTTPS maven repositories

server/src/main/java/org/cloudfoundry/identity/uaa/client/ClientAdminEndpoints.java
Using the native Java concurrent types AtomicInteger and
ConcurrentHashMap makes it unnecessary to also use the `synchronized`
keyword.
The example in the atomicvars guide shows how AtomicInteger can be used
for a simple counter:
https://docs.oracle.com/javase/tutorial/essential/concurrency/atomicvars.html
=> Remove unnecessary use of synchronized

server/src/main/java/org/cloudfoundry/identity/uaa/user/JdbcUaaUserDatabase.java, server/src/test/java/org/cloudfoundry/identity/uaa/user/JdbcUaaUserDatabaseTests.java
Any time a user is retrieved using this class, the getAuthorities method is executed to retrieve all of the user's direct and indirect group memberships recursively. 
As mentioned in #463 by my colleague @mwdb the number of SQL queries used to do this grows with the number of scopes assigned.
As the methods are called very frequently, this highly increases the load on the database. With this PR the number of SQL queries is reduced. According to our performance tests this highly increases the performance of the database.
=> Change getAuthorities to reduce number of executed SQL-Statements

server/src/main/java/org/cloudfoundry/identity/uaa/login/AccountSavingAuthenticationSuccessHandler.java, server/src/main/java/org/cloudfoundry/identity/uaa/login/LoginInfoEndpoint.java, server/src/test/java/org/cloudfoundry/identity/uaa/login/AccountSavingAuthenticationSuccessHandlerTest.java, server/src/test/java/org/cloudfoundry/identity/uaa/login/LoginInfoEndpointTests.java, uaa/src/test/java/org/cloudfoundry/identity/uaa/login/LoginMockMvcTests.java, uaa/src/test/java/org/cloudfoundry/identity/uaa/scim/endpoints/PasswordResetEndpointMockMvcTests.java
* fix #563
* Encode Cookie Saved-Account-xx in AccountSaving
* Decode Cookie Saved-Account-xx in LoginInfoEndpoint
* Add test for invalid cookie
=> Encode cookies to be compliant with Tomcat 8.5x

server/src/main/java/org/cloudfoundry/identity/uaa/util/UaaUrlUtils.java, server/src/test/java/org/cloudfoundry/identity/uaa/util/UaaUrlUtilsTest.java
As reported in cloudfoundry/uaa#562, when the login hostname begins with login,
then generation of the redirect_uri sent to OIDC providers should look like
this before urlencoding:
https://login.domain/login/callback/ALIAS
instead it looks like this:
https://login/callback/ALIAS
Which causes the Google OIDC provider to reject the request due to a non-whitelisted redirect_uri.
This fixes that bug and also adds tests.
=> Fix BaseURL generation when hostname matches URL

docs/google-oidc-provider.md
This might fix #565
Prior to our v251 to v253 CF upgrade, logging in with google OpenID Connect seemed to be working, however once we'd upgraded to v253 we encountered the error: "There was an error when authenticating against the external identity provider: Could not verify token signature."
As suggested in #565 , a tokenKeyURL has been added, and this appears to make the problem go away. 
I'm unclear if it is intentional that `tokenKeyUrl` is now required. There didn't appear to be anything in the release notes describing the config changes that needed to be made.
=> Add tokenKeyUrl to sample Google OIDC config

model/src/main/java/org/cloudfoundry/identity/uaa/provider/SamlIdentityProviderDefinition.java, server/src/main/java/org/cloudfoundry/identity/uaa/provider/saml/BootstrapSamlIdentityProviderConfigurator.java, server/src/main/java/org/cloudfoundry/identity/uaa/provider/saml/LoginSamlAuthenticationProvider.java, server/src/main/java/org/cloudfoundry/identity/uaa/provider/saml/LoginSamlEntryPoint.java, server/src/test/java/org/cloudfoundry/identity/uaa/provider/saml/BootstrapSamlIdentityProviderConfiguratorTests.java, server/src/test/java/org/cloudfoundry/identity/uaa/provider/saml/SamlIdentityProviderConfiguratorTests.java, server/src/test/java/org/cloudfoundry/identity/uaa/provider/saml/SamlIdentityProviderDefinitionTests.java, uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/providers/IdentityProviderEndpointsDocs.java, uaa/src/test/java/org/cloudfoundry/identity/uaa/provider/saml/LoginSamlAuthenticationProviderTests.java
This PR allows for setting a `RequestedAuthnContext` in the SAMLRequest generated when UAA is operating as a SAML SP.  This is accomplished by adding a new property to `login.saml.providers` named `authnContext`.
For example:
```yaml
login:
saml:
providers:
cloud.gov:
authnContext:
- foo
- bar
- baz
idpMetadata: |
...
```
Would produce a SAMLRequest with this `RequestedAuthnContext`:
```xml
<saml2p:RequestedAuthnContext Comparison="exact">
<saml2:AuthnContextClassRef xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion">foo</saml2:AuthnContextClassRef>
<saml2:AuthnContextClassRef xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion">bar</saml2:AuthnContextClassRef>
<saml2:AuthnContextClassRef xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion">baz</saml2:AuthnContextClassRef> …
```
=> When acting as a SAML SP allow configuration of RequestedAuthnContext

server/src/main/resources/templates/web/login.html, uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/feature/LoginIT.java, uaa/src/test/java/org/cloudfoundry/identity/uaa/login/LoginMockMvcTests.java
When login page is left open until the point of expiry of CSRF token and the user goes on to submit their credentials, they are shown with the CSRF error `Invalid login attempt, request does not meet our security standards, please try again`. This can be avoided by performing a client-side page reload using `meta-refresh` when the CSRF token expires.
=> Reload login when CSRF token expires

model/src/main/java/org/cloudfoundry/identity/uaa/provider/AbstractXOAuthIdentityProviderDefinition.java, server/src/main/java/org/cloudfoundry/identity/uaa/provider/oauth/XOAuthAuthenticationManager.java, server/src/test/java/org/cloudfoundry/identity/uaa/provider/oauth/XOAuthAuthenticationManagerTest.java, uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/providers/IdentityProviderEndpointsDocs.java
As per [spec](https://tools.ietf.org/html/rfc6749#section-2.3.1), client credentials can be specified using either methods.
=> OIDC token endpoint needs to support client authorization in either POST body or Basic auth

server/src/main/java/org/cloudfoundry/identity/uaa/oauth/UaaTokenServices.java
Instead of reading the user from the database twice (one time for the access token, one time for the refresh token), pass the user object as parameter to the createRefreshToken method.
As there should be no difference in the behavior (only difference being less calls to the database), I included no additional tests in this PR.
=> Pass user object as parameter for refresh token

docs/UAA-APIs.rst
The JSON object should be named "az_attr" instead of "additionalAuthorizationAttributes". See the following code:
https://github.com/cloudfoundry/uaa/blob/fe946fdc871027fcea9278e97c09cbf270831cf4/server/src/main/java/org/cloudfoundry/identity/uaa/oauth/UaaTokenServices.java#L840
=> Fix documentation of additional authorization attributes

server/src/main/java/org/cloudfoundry/identity/uaa/authentication/event/UserAuthenticationFailureEvent.java
If this null check was ever true the `user.getUsername()` call would
raise a NullPointerException.
These events only occur when user passwords don't match, more precisely
the event is only created here:
org/cloudfoundry/identity/uaa/authentication/manager/AuthzAuthenticationManager.java:107
In this case the user object has already been null checked.
=> Remove null check on UserAuthenticationFailureEvent

server/src/main/java/org/cloudfoundry/identity/uaa/login/LoginInfoEndpoint.java, uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/feature/LoginIT.java
When the user session expires, this `form_redirect_uri` is used to retain the context. But, the value is lost when login page is reloaded due to any error (ie incorrect password, csrf). This fix adds the value to the model if present in the original request
=> Add form_redirect_uri to login page during reload

server/src/main/java/org/cloudfoundry/identity/uaa/authentication/PasscodeAuthenticationFilter.java
The use of this method from hsqldb causes problem if jar is not available
The dependent library is not needed for usage if mysql or postgesql therefore we removed it.
However with this dependency it is a hard requirement which should not be the case.
If you check the internals of isEmpty of hsqldb then it is the same if you call isBlank from apache
see also
http://technohandle.blogspot.de/2011/01/stringutilsisemtpty-vs.html
=> use isBlank form apache instead of isEmpty for hsqldb

model/src/main/java/org/cloudfoundry/identity/uaa/oauth/token/Claims.java, server/src/main/java/org/cloudfoundry/identity/uaa/oauth/CheckTokenEndpoint.java, server/src/test/java/org/cloudfoundry/identity/uaa/oauth/CheckTokenEndpointTests.java, uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/CheckTokenEndpointIntegrationTests.java
Documentation says that with authorities additional claims
can be added into JWT.
However with /check_token this fails because of invalid json
object if you add here a string map.
See:
https://github.com/cloudfoundry/uaa/blob/master/docs/UAA-APIs.rst
Example:
authorities={"az_attr":{"external_group":"domain\\group1","external_id":"abcd1234"}}
=> Fix type for claim az_attr

server/src/main/resources/org/cloudfoundry/identity/uaa/db/hsqldb/V4_9_1__Extend_client_scopes_authorities.sql, server/src/main/resources/org/cloudfoundry/identity/uaa/db/mysql/V4_9_1__Extend_client_scopes_authorities.sql, server/src/main/resources/org/cloudfoundry/identity/uaa/db/postgresql/V4_9_1__Extend_client_scopes_authorities.sql, server/src/main/resources/org/cloudfoundry/identity/uaa/db/sqlserver/V4_9_1__Extend_client_scopes_authorities.sql, server/src/test/java/org/cloudfoundry/identity/uaa/db/ClientDetailsSupportsExtendedAuthoritesAndScopes.java, server/src/test/java/org/cloudfoundry/identity/uaa/db/RevocableTokenTableTest.java
Hi,
as discussed, we want to extend the fields storing scopes and authorities for oauth clients. 
As simply doubling it is not supported by all databases, I decided to go for text-types, which are also used e.g. for identity_zone config.
=> Extend scope and authorities fields for oauth clients

server/build.gradle
omit bsh-core-2.0b4.jar because of CVE-2016-2510
=> omit not needed libs

model/src/main/java/org/cloudfoundry/identity/uaa/util/UaaStringUtils.java, server/src/test/java/org/cloudfoundry/identity/uaa/util/UaaStringUtilsTest.java
@jhamon  I created extra PR to #781  but the test shows the problem
see https://www.asciitable.com/ 
The rule A-z excludes A-Z and a-z but also all chars between Z - a [\]^_`
=> Test for PR 781

model/src/main/java/org/cloudfoundry/identity/uaa/util/UaaStringUtils.java
There is a typo in the regex pattern consisting of characters that don't need to be escaped. The pattern "A-z" actually includes all the characters between the uppercase A and lowercase Z, namely "[", "\", "]", "^", "_", and "`". Without this fix, those characters are treated as regex characters instead of string literals.
=> Escape the correct regex characters

model/src/main/java/org/cloudfoundry/identity/uaa/zone/IdentityZoneConfiguration.java, server/src/main/java/org/cloudfoundry/identity/uaa/util/UaaTokenUtils.java, server/src/test/java/org/cloudfoundry/identity/uaa/oauth/UaaTokenServicesTests.java, uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/zones/IdentityZoneEndpointDocs.java
The default zone uses a YAML configuration entry, which remains as it is
Add test for new property
Old:
The other zones use automatically a generated issuer.uri which enforce an indivdual trust configuration for each Zone of UAA
New:
Move issuer.uri to Config in zone configuration and make use of the property if the entry is not null
This allows that a zone can have an own configured issuer.uri 
Allows to combine the trust of different zones to one trust, simply using same issuer
=> Use issuer.uri from zone configuration

server/src/main/java/org/cloudfoundry/identity/uaa/zone/IdentityZoneResolvingFilter.java, server/src/test/java/org/cloudfoundry/identity/uaa/zone/IdentityZoneResolvingFilterTests.java
* convert internal hostnames from yml into lower case
* compare hostname check with lower case.
should solve issue #730
=> resolve lower hostnames only

server/src/main/java/org/cloudfoundry/identity/uaa/oauth/UaaTokenServices.java, server/src/test/java/org/cloudfoundry/identity/uaa/oauth/CheckTokenEndpointTests.java, uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/CheckTokenEndpointIntegrationTests.java
In addition to pull request #729 add a type check for az_attr
and prevent write if type is not valid.
Remark: with PR #729 the validation already fails if az_attr claim
has not correct type, however now we prevent that a JWT is created with
an invalid az_attr input.
The result JWT does not contain the az_attr claim if type check fails
=> Add input validation for az_attr

server/src/main/java/org/cloudfoundry/identity/uaa/provider/saml/LoginSamlAuthenticationProvider.java, server/src/test/java/org/cloudfoundry/identity/uaa/provider/saml/LoginSamlAuthenticationProviderTests.java
**Scenario**
* User created with Identity Provider (SAML)
* User logon (UAA)
* User deleted (on provider)
* User created again with same email address and new user id (SAML)
* User logon (UAA)
**Actual behavior**
The shadow user is found by email. If no other attributes have changed, the user record will NOT be updated since the `userModified` flag is not set in this case. The token issued from UAA contains a wrong/outdated user identifier.
**Expected behavior**
The shadow user is found by email and the record is updated with the new user id.
**Change**
* set `userModified` when the user has been found via email and `modifyUsername` is called
* add test to verify the described behavior
=> Saml Provider: ensure username update

shared_versions.gradle
since version 1.0.0 is not compatible with hibernate 4.3.x
follow-up to https://github.com/cloudfoundry/uaa/pull/832
=> update javax.validation 

build.gradle
in addition to https://github.com/cloudfoundry/uaa/commit/0192d1d05e039136ae64944ed0afbbac9a06dd12
Debugging of integration tests is useful
and before I had to add options always manually
by changing build.gradle
=> add debug options if in profile activated

server/src/main/java/org/cloudfoundry/identity/uaa/scim/endpoints/ScimGroupEndpoints.java, server/src/test/java/org/cloudfoundry/identity/uaa/scim/endpoints/ScimGroupEndpointsTests.java
Addresses #824 
Currently all members of all Groups are queried, even if the members are not included in the response.
This PR changes this behavior to only query the members on the /Groups endpoint, when they are actually returned in the response.
For a larger amount of groups, this is a huge performance increase.
=> SCIM Groups Endpoint: only query members if needed
